version: '3'

services:
  base: &base
    build: .
    ports:
      - '3000:3000'
    volumes:
      - marleys_boon_gems:/usr/local/bundle
      - .:/app
    env_file: .env
    working_dir: /app
    environment:
      - MB_CONTENTFUL_SPACE_ID
      - MB_CONTENTFUL_ENVIRONMENT_ID
      - MB_CONTENTFUL_ACCESS_TOKEN

  app:
    <<: *base
    command: ['./bin/start']

  tests:
    <<: *base
    command: ['./bin/tests']

volumes:
  marleys_boon_gems:
