version: '3'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - marleys_boon_gems:/usr/local/bundle
      - .:/app
    env_file: .env
    working_dir: /app
    environment:
      - MB_CONTENTFUL_SPACE_ID
      - MB_CONTENTFUL_ENVIRONMENT_ID
      - MB_CONTENTFUL_ACCESS_TOKEN
    command: ['./bin/start']

volumes:
  marleys_boon_gems:
